---
ssh_port: 22
firewall_ports:
    - "{{ app_port }}"
    - "{{ management_server_port }}"
    - "{{ minio_api_port }}"
    - "{{ minio_console_port }}"
web_ports:
    - "{{ http_port }}"
    - "{{ https_port }}"